dbt_models:
  target:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('DBT_PRJ') }}"
      schema: trips_data_all
      threads: 6
      job_execution_timeout_seconds: 600 
      location: US